/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.ControllerRegisterBook;
import controller.ControllerRegisterLoan;
import controller.ControllerRegisterMatAudiv;
import domain.AudiVisulMaterial;
import domain.Book;
import domain.Loan;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author Leonardo
 */
public class ViewLongs extends javax.swing.JFrame {

    /**
     * Creates new form ViewLongs
     */
     
    public static String ID;
    public static String password;
    public ArrayList<Book> listBook = new ArrayList();
    public ArrayList<AudiVisulMaterial> listMatAudi = new ArrayList();
    public ViewLongs() {
        initComponents();
        login l = new login();
        ID = l.name;
        listBook= ControllerRegisterBook.read();
        listMatAudi = ControllerRegisterMatAudiv.read();
        
      //  JOptionPane.showMessageDialog(this, ID);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        info = new javax.swing.JTextArea();
        search = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        request = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        info.setColumns(20);
        info.setRows(5);
        jScrollPane1.setViewportView(info);

        search.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                searchKeyReleased(evt);
            }
        });

        jLabel1.setText("Enter the name of the item you want");

        request.setText("REQUEST");
        request.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                requestActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(85, 85, 85)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(123, 123, 123)
                        .addComponent(search, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(160, 160, 160)
                        .addComponent(request))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(69, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(search, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(request)
                .addGap(31, 31, 31))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void searchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchKeyReleased
        // TODO add your handling code here:
        info.setText("");
        String result ="";
        String resultMA ="";
        int cont =0;        
        for(int i=0; i<listBook.size(); ++i)
            if(ControllerRegisterLoan.seekerBookName(search.getText().trim(), listBook.get(i)) || ControllerRegisterLoan.seekerBookISBN(search.getText().trim(), listBook.get(i))){
                if(ControllerRegisterLoan.seekerBookName(search.getText().trim(), listBook.get(i)) || ControllerRegisterLoan.seekerBookISBN(search.getText().trim(), listBook.get(i)))
                {
                result +=listBook.get(i).toString();
                cont++;
                System.out.print(cont);
                }
                
                }
        
         for(int i=0; i<listMatAudi.size(); ++i)
         {
             if(ControllerRegisterLoan.seekerMaterialCode(search.getText().trim(), listMatAudi.get(i)) || ControllerRegisterLoan.seekerMaterialName(search.getText().trim(), listMatAudi.get(i))   )
             {
                 resultMA+=listMatAudi.get(i).toString();
             }
         }
         info.setText(result+"\n"+resultMA);
        
    }//GEN-LAST:event_searchKeyReleased

    private void requestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_requestActionPerformed
        // TODO add your handling code here:
        String value = search.getText().trim();
        Book book;
        
        //try
        //{
            book = ControllerRegisterLoan.bookSelected(listBook, value);
        AudiVisulMaterial material;
        material = ControllerRegisterLoan.materialSelected(listMatAudi, value);
        
        if(book != null || material != null)
        {
                if (book != null) {
                    java.util.Date date = new Date();
                    java.util.Date dateD;
                     dateD = ControllerRegisterLoan.addDaysDate(date,ControllerRegisterLoan.days(0) );
                    Loan loan = new Loan(book.getCode(),book.getTitle(),ID,dateD);
                     ArrayList<Loan> listLoans = new ArrayList<Loan>();
                    listLoans=ControllerRegisterLoan.read();
                     loan.setID(listLoans.size()+1);
                   
                   
                    JOptionPane.showMessageDialog(this, book.getTitle());
               
                     try{
                         
                         boolean v=ControllerRegisterLoan.write(loan);
                         System.out.print(v);
                         if(v){
                         JOptionPane.showMessageDialog(this,"The item has been registered: "+loan.getName()+"\n"+"The delivery date: " +loan.getDeliveryDate());
                         }
                     }catch(Exception e)
                     {
                         JOptionPane.showMessageDialog(this,"the item  has  not been registered");
                     }
                             
                     ControllerRegisterLoan.write(loan);
                     
                     
                }
                if (material != null) {
                    JOptionPane.showMessageDialog(this, material.getType());
                    java.util.Date date = new Date();
                    java.util.Date dateD;
                   dateD = ControllerRegisterLoan.addDaysDate(date,ControllerRegisterLoan.days(1) );
                    Loan loan = new Loan(String.valueOf(material.getCode()), material.getType(), ID, date);
                     ArrayList<Loan> listLoans = new ArrayList<Loan>();
                     listLoans=ControllerRegisterLoan.read();
                    loan.setID(listLoans.size()+1);
                  
                     try{
                         
                        
                         if (ControllerRegisterLoan.write(loan)){
                         JOptionPane.showMessageDialog(this," The item has been registered: "+loan.getName() +"\n"+" The delivery date is: " +loan.getDeliveryDate());
                     }
                         else {
                                 JOptionPane.showMessageDialog(this,"FALSE");}
                     }catch(Exception e)
                     {
                         JOptionPane.showMessageDialog(this,"the item not has been registered");
                     }
                             
                     ControllerRegisterLoan.write(loan);

                }
            }
        else
        {
             JOptionPane.showMessageDialog(this, "Error the article not exits" , "Error", JOptionPane.ERROR_MESSAGE);
        } 
       
       
        
        
   
        
        
        
        
        
        
    }//GEN-LAST:event_requestActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewLongs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewLongs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewLongs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewLongs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewLongs().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea info;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton request;
    private javax.swing.JTextField search;
    // End of variables declaration//GEN-END:variables
}
